name: Practice
on: push
env:
  MY_VAR: my env var
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MY_VAR: $MY_VAR"
          echo 'MY_VAR: $MY_VAR' # it does not work
          echo "MY_VAR: ${{ env.MY_VAR }}"
